### ISSUE TITLE
New Comparison View: Untriaged Issues

### ISSUE THREAD

**Issue by smarr** [smarr/ReBenchDB#159]
- http://localhost:33333/TruffleSOM/compare-new/a8ce2161b66a43e1e40c49dc36181740a19dd515..20a2be6391a4815d8887278ee1a029c13eeb9ac6

```
ReBenchDB/src/backend/compare/html/stats-row-buttons-info.html:21
      19|       const baseTrial = d.profileTrialIdBase.trialid;
      20|       const changeTrial = d.profileTrialIdChange.trialid;
   >> 21| %}<button type="button" class="btn btn-sm btn-profile" data-content="{%= f.dataSeriesIds(d.dataSeries, d.profileTrialIdBase.runid, baseTrial, changeTrial) %}"></button>
      22| {%
      23|    }
      24| %}<button type="button" class="btn btn-sm btn-timeline" data-content='{%- JSON.stringify(
  
  Cannot read properties of undefined (reading 'base')
      at Module.dataSeriesIds (ReBenchDB/src/shared/data-format.ts:129:21)
      at eval ("ReBenchDB/src/backend/compare/html/stats-row-buttons-info.html":48:28)
      at stats-row-buttons-info (ReBenchDB/node_modules/ejs/lib/ejs.js:703:17)
      at include (ReBenchDB/node_modules/ejs/lib/ejs.js:701:39)
      at eval ("ReBenchDB/src/backend/compare/html/stats-row.html":109:17)
      at stats-row (ReBenchDB/node_modules/ejs/lib/ejs.js:703:17)
      at include (ReBenchDB/node_modules/ejs/lib/ejs.js:701:39)
      at eval ("ReBenchDB/src/backend/compare/html/stats-tbl.html":21:19)
      at stats-tbl (ReBenchDB/node_modules/ejs/lib/ejs.js:703:17)
      at include (ReBenchDB/node_modules/ejs/lib/ejs.js:701:39)
```

**Comment by smarr** [comment]
Resolved by #164
